language: python
python: "3.6"
dist: xenial

stages:
  - test
  - deploy

cache:
  pip: true

jobs:
  include:
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - pytest --cov arus
      after_success:
        - codecov
    - stage: deploy
      before_deploy:
        - poetry build
      deploy:
        provider: pypi
        user: $PYPI_USER
        password: $PYPI_PASS
        skip_existing: true
        skip_cleanup: true
