# site config
site_name: ARUS Python package
site_url: https://qutang.github.io/arus/
site_description: ARUS package provides a computational framework to manage and process ubiquitous sensory data for human activity recognition.
site_author: Qu Tang

# repo
repo_name: qutang/arus
repo_url: https://github.com/qutang/arus
edit_uri: blob/master/docs/

#Copyright text in the footer
copyright: 2020 © Qu Tang

# Customization
extra:
  social:
    - icon: fontawesome/solid/at
      link: https://qutang.dev
    - icon: fontawesome/brands/github-alt
      link: https://github.com/qutang
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/qutang

# Material theme for MkDocs : https://github.com/squidfunk/mkdocs-material/
theme:
  name: material
  palette:
    primary: white
    accent: orange
    scheme: default
  icon:
    logo: material/run-fast
    repo: fontawesome/brands/github-alt
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    - instant
  hljs_style: github
  nav_style: light
  navigation_depth: 2
  include_homepage_in_sidebar: false
  prev_next_buttons_location: none

extra_css:
  - assets/css/extra.css
  - assets/css/mkapi.css

plugins:
  - search
  - mkapi:
      src_dirs: [arus]
  - minify:
      minify_html: true
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: "true"
  - markdown.extensions.attr_list
  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite:
      guess_lang: false
  - smarty
  - toc:
      permalink: "#"
      baselevel: 2

# Site navigation in the side bar
nav:
  - Home:
      - Overview: "README.md"
      - License: "LICENSE.md"
      - Code Of Conduct: "CODE_OF_CONDUCT.md"
      - Changelogs: "changelogs/index.md"
  - Use the package:
      - Overview: "tutorials/overview.md"
      - Command line tool: "tutorials/commandline.md"
  - API:
      - Dataflow:
          - Generator: "api/generator.md"
  # - Examples:
  #     - Streams:
  #         - "examples/streams/run_actigraph_sensor_stream.md"
  #         - "examples/streams/run_mhealth_annotation_stream.md"
  #         - "examples/streams/run_mhealth_sensor_stream.md"
  #     - Scheduler: "examples/scheduler/run_scheduler.md"
  #     - Dataset:
  #         - "examples/dataset/process_raw_dataset.md"

use_directory_urls: true
