
SENSOR_PLACEMENTS = ['DW', 'NDW', 'DA', 'NDA', 'DT', 'NDT', 'DH', 'NDH']
TIMESTAMP_COL = 'HEADER_TIME_STAMP'
START_TIME_COL = 'START_TIME'
STOP_TIME_COL = 'STOP_TIME'
FEATURE_SET_TIMESTAMP_COLS = [TIMESTAMP_COL, START_TIME_COL, STOP_TIME_COL]
FEATURE_SET_PID_COL = 'PID'
FEATURE_SET_PLACEMENT_COL = 'PLACEMENT'
ANNOTATION_LABEL_COL = 'LABEL_NAME'

META_FOLDER = 'MetaCrossParticipants'
PROCESSED_FOLDER = 'DerivedCrossParticipants'
MASTER_FOLDER = "MasterSynced"

META_LOCATION_MAPPING_FILENAME = 'location_mapping.csv'
META_SUBJECTS_FILENAME = 'subjects.csv'
META_CLASS_CATEGORY = 'class_category.csv'

FILE_TIMESTAMP_FORMAT = '%Y-%m-%d-%H-%M-%S-%f'
FILE_TIMESTAMP_FORMAT_WITH_TZ = '%Y-%m-%d-%H-%M-%S-%f-%z'

SENSOR_FILE_TYPE = 'sensor'
ANNOTATION_FILE_TYPE = 'annotation'
FEATURE_SET_FILE_TYPE = 'set'
FEATURE_FILE_TYPE = 'feature'
CLASS_FILE_TYPE = 'class'

FILE_TYPES = [SENSOR_FILE_TYPE, ANNOTATION_FILE_TYPE,
              FEATURE_SET_FILE_TYPE, FEATURE_FILE_TYPE, CLASS_FILE_TYPE]
